name: Tests

on:
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    name: Maven Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'corretto'
          cache: 'maven'
      - name: Run Tests
        run: ./mvnw test
        env:
          CHROME_OPTIONS: --remote-allow-origins=*;--disable-gpu;--no-sandbox;--disable-dev-shm-usage;--headless=new;--window-size=1920,1080
          APP_OPTIONS: host=localhost;port=8000;admin.username=admin;admin.password=Asdf.1234.qpwoei
          CI_RUN: true
