name: Tests

on:
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    name: Maven Verify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'corretto'
          cache: 'maven'
      - name: Maven Verify
        run: mvn verify -Dlocal.chrome_options2="--remote-allow-origins=*;--disable-gpu;--headless=new;--disable-dev-shm-usage;--no-sandbox;--window-size=1920,1080"
