name: Tests

on:
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    name: Maven Verify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'corretto'
          cache: 'maven'
      - name: Set chrome options
        uses: dschanoeh/change-property@v1
        with:
          file: src/test/resources/local.properties
          property: local.chrome_options
          value: --headless --disable-dev-shm-usage --no-sandbox
      - name: Maven Verify
        run: mvn verify
